# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d11b89eb60b127ba48e1bbca566d3b3ba411df8449d2718701246cb3dac4fc0601910e3e8760d162200d2b959eaa413329ffb773ff5fc7ec2f1fff0446124bc0

test:
  secret_key_base: 06c12cb7509a90719f474b2a183ed05be8b6b2f3732821d1f7428f2788d258c3a558dc0ec9c15f9455365d8aa2797302b5fd1111a77c7d7e8761032c19459561

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
